# Generated by Django 4.1 on 2022-09-17 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVelez', '0002_empleados_legajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='email',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='empleados',
            name='sueldo',
        ),
        migrations.RemoveField(
            model_name='sociosplenos',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='sociosplenos',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='sociosplenos',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='sociosplenos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sociosplenos',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='sociosplenos',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='sociosplenos',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='sociosplenos',
            name='provincia',
        ),
        migrations.RemoveField(
            model_name='sociossemiplenos',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='sociossemiplenos',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='sociossemiplenos',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='sociossemiplenos',
            name='email',
        ),
        migrations.RemoveField(
            model_name='sociossemiplenos',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='sociossemiplenos',
            name='localidad',
        ),
        migrations.RemoveField(
            model_name='sociossemiplenos',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='sociossemiplenos',
            name='provincia',
        ),
    ]
