# Generated by Django 4.1 on 2022-09-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVelez', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='imagen',
            field=models.ImageField(null=True, upload_to='avatares'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
