# Generated by Django 4.1 on 2022-09-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVelez', '0005_empleados_imagen_delete_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleados',
            name='imagen',
        ),
    ]
