# Generated by Django 4.1 on 2022-09-18 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVelez', '0007_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avatar',
            name='imagen',
        ),
    ]
