# Generated by Django 4.1 on 2022-09-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVelez', '0008_remove_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
