# Generated by Django 4.1 on 2022-09-18 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVelez', '0010_rename_imagen_avatar_imagen_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user',
            new_name='user_avatar',
        ),
    ]
