# Generated by Django 4.1 on 2022-09-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVelez', '0011_rename_user_avatar_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='user_avatar',
            new_name='user',
        ),
    ]
