# Generated by Django 4.1 on 2022-09-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppVelez', '0012_rename_user_avatar_avatar_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='imagen_avatar',
            new_name='imagen',
        ),
    ]
